### ISSUE TITLE
Mods?

### ISSUE THREAD

**Issue by rlex** [SQLJames/factorio-server-charts#12]
Hello, i see UPDATE_MODS_ON_START env variable on pod, but no way to install mods from helm chart. Am i missing something?

**Comment by SQLJames** [comment]
To install the mod, you need to copy the zipped file into the mods directory located under the user data directory without unzipping it.
I was able to take a look at this today. Looks like the best option would be to utilize the documented mod portal API.
https://wiki.factorio.com/Mod_portal_API. 
I would also like to include other github.com mods or other to download at the same time if not listed on the portal.
- Create an array of mod names listed on the portal E.G. 
```
mods:
  portal:
    - Krastorio2
  unofficial:
    - something.com/download.zip
```
For the official mods:
- We can run an init container that would curl the array of mod names  E.G. https://mods.factorio.com/api/mods/{name}
- Use jq to parse the json object given back to us to validate the mod has a valid version for the running factorio server.
- Use jq to pull that download link, if available. if not available, we need to log this somewhere. 
- curl to download the mod and place it in the folder E.G. https://mods.factorio.com/{download_url}?username={username}&token={token}
For the baseline URLs
- We just curl the mod url
- place them in the mod folder
The end user would need to be responsible for checking version compatibility.

**Comment by SQLJames** [comment]
Updated in https://github.com/SQLJames/factorio-server-charts/pull/14
You can now download mods into your factorio container.

**Comment by Vanderscycle** [comment]
Hey not to add an edge case to the solid work you did, but what about mods with lots of dependencies that are normally downloaded with the main package like `space ex` mod? 

I am asking because I can't seem to be able to download the pace exploration mod.
``` yaml
mods:
  enabled: true
  # in order to use the mods portal you will need to specify the username and token in the server_settings.
  # name is determined by the url, it will be the last part of the url, not the title of the mod.
  portal:
    - space-exploration
    - [...] more to be added later
```

BTW, your helm chart allowed me to bridge the huge knowledge gap needed to have argocd/kustomize/helm in a declarative gitops pattern to work. 

Thank you,
