### ISSUE TITLE
Space exploration mod configuration

### ISSUE THREAD

**Issue by SQLJames** [SQLJames/factorio-server-charts#24]
Hey not to add an edge case to the solid work you did, but what about mods with lots of dependencies that are normally downloaded with the main package like `space ex` mod? 

I am asking because I can't seem to be able to download the space exploration mod.
``` yaml
mods:
  enabled: true
  # in order to use the mods portal you will need to specify the username and token in the server_settings.
  # name is determined by the url, it will be the last part of the url, not the title of the mod.
  portal:
    - space-exploration
    - [...] more to be added later
```

BTW, your helm chart allowed me to bridge the huge knowledge gap needed to have argocd/kustomize/helm in a declarative gitops pattern to work. 

Thank you,

_Originally posted by @Vanderscycle in https://github.com/SQLJames/factorio-server-charts/issues/12#issuecomment-1364435858_

**Comment by SQLJames** [comment]
First of all, thanks for the shoutout, I wouldn't have been able to learn as much as I did as well without this project. 

Secondly, I have been a bit absent lately on this project as I have been rebuilding my k8s cluster to and moving my home lab around(no testing location).

Finally, addressing your issue, can I ask you to exec into the container and see what is being downloaded to the `/factorio/mods` folder?

**Comment by Vanderscycle** [comment]
No worries, its the holidays. After `exec --stdin` into the pod I do see the space exploration mod zip files but not in the game lobby.

The content of the mod folder:
```bash
drwxr-xr-x    1 factorio factorio       390 Dec 24 01:43 .
drwxrwxrwx    1 factorio factorio       220 Dec 24 01:43 ..
-rw-r--r--    1 factorio factorio    460136 Dec 24 01:43 LogisticTrainNetwork_1.18.1.zip
-rw-r--r--    1 factorio factorio     40446 Dec 24 01:43 Squeak
-rw-r--r--    1 factorio factorio    126398 Dec 24 01:43 informatron_0.3.1.zip
-rw-r--r--    1 factorio factorio    889969 Dec 24 01:43 jetpack_0.3.8.zip
-rw-r--r--    1 factorio factorio       529 Dec 24 01:43 mod-list.json
-rw-r--r--    1 factorio factorio       524 Dec 24 01:43 mod-settings.dat
-rw-r--r--    1 factorio factorio     44800 Dec 24 01:43 robot_attrition_0.5.12.zip
-rw-r--r--    1 factorio factorio  45431223 Dec 24 01:43 space-exploration-graphics_0.6.14.zip
-rw-r--r--    1 factorio factorio   3244072 Dec 24 01:43 space-exploration_0.6.94.zip
bash-5.0# pwd
/factorio/mods
bash-5.0# 
```

The in-game lobby:
![image](https://user-images.githubusercontent.com/52706578/209418885-96492ba9-d508-44e9-9135-1864aba610b1.png)

When installing space-exploration downloads a sizeable amount of other mods. I suspect that the space exploration mod needs all of them to show in-game. Will tinker later, by manually adding them all to the `values.yaml` file.
![image](https://user-images.githubusercontent.com/52706578/209418971-9352a349-565e-4b0c-954a-f7175772b3e4.png)

**Comment by SQLJames** [comment]
Based on what you mentioned, I suspect that to be the case. It looks like if you had a normal factorio server you would just be able to manage the mods through the ui but because of the way the mod injection is working, I believe you will need to specify the dependencies in the chart as well. Based on the link below, he has quite a list of required mods more information can be found on their site though.

[Recommended mods with dependencies](https://spaceexploration.miraheze.org/wiki/Recommended_Mods#Required_Dependencies)

**Comment by Vanderscycle** [comment]
We can close the ticket since I don't think there's anything wrong with the helm chart. I will raise an issue with the the Space Exploration discord (where they do all the tracking)

For posterity here's all the mods and a few QOL/extras required for space ex
```yaml
mods:
  enabled: true
  # in order to use the mods portal you will need to specify the username and token in the server_settings.
  # name is determined by the url, it will be the last part of the url, not the title of the mod.
  portal:
    # https://spaceexploration.miraheze.org/wiki/Recommended_Mods#Required_Dependencies
    # Recommended
    - ModuleInserterSimplified
    - aai-vehicles-ironclad
    - grappling-gun
    - bullet-trails
    - equipment-gantry
    - textplates
    - combat-mechanics-overhaul
    - RecipeBook
    # QOL
    - even-distribution
    - AutoTrash
    - LogisticRequestManager
    - BottleneckLite
    - Squeak Through
    - LogisticTrainNetwork
    # spaceX
    - space-exploration-graphics
    - space-exploration-graphics-2
    - space-exploration-graphics-3
    - space-exploration-graphics-4
    - space-exploration-graphics-5
    - space-exploration-menu-simulations
    - shield-projector
    - aai-containers
    - aai-industry
    - aai-signal-transmission
    - simhelper
    - space-exploration-graphics
    - robot_attrition
    - alien_biomes
    - informatron
    - jetpack
    - space-exploration-postprocess #WARN: causes crashing
    - space-exploration
 ```

**Comment by SQLJames** [comment]
Just wanted to follow up before I close this, did you get it downloaded?

**Comment by SQLJames** [comment]
@Vanderscycle I just wanted to follow up, if you were able to get this downloaded, would you mind placing the values for the mod section here for completion.

**Comment by Vanderscycle** [comment]
```yaml
rcon:
  external: false
  # passwordSecret: 'test'

# nodeSelector:
  # kubernetes.io/hostname: space-exploration # this makes it easier for firewall rules and makes sure things dont change
  #
resources:
  requests:
    cpu: 250m

# making sure the game doesnt auto update on redeploy
# https://hub.docker.com/r/factoriotools/factorio/
image:
  tag: stable


persistence:
  enabled: true

factorioServer:
  save_name: "space-exploration"
  update_mods_on_start: true

#needed if playing online
admin_list: [ 'VanofHoogen' ] # put your admins based on factorio names
# - "john_doe"
# - "jane_doe"

white_list: [ ] # put the people you want to play with you based on factorio names
# - "john_doe"
# - "jane_doe"
#
service:
  type: NodePort
  port: 31497

  # externalIPs:
  #  - "172.105.1.131"

server_settings:
  name: '[BETA] helm-kubernetes-argocd-SpaceEx'
  description: 'unstable and experimental deployment method by me. Use at own risk and expect loss of data'
  tags:
    - modded
    - helm
    - experimental

  visibility:
    public: true
  require_user_verification: true
  autosave_only_on_server: false

account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  # accountSecret: ''
  # Your factorio.com login credentials. Required for games with visibility public
  username: ''
  # password: ''
  # Authentication token. May be used instead of password above.
  token: ''

serverPassword:
  # password required to log into the factorio server
  game_password: 'kubernetes'
  # Existing Secret containing a `game_password` data entry
  passwordSecret: ''

mods:
  enabled: true
  # in order to use the mods portal you will need to specify the username and token in the server_settings.
  # name is determined by the url, it will be the last part of the url, not the title of the mod.
  portal:
    # https://spaceexploration.miraheze.org/wiki/Recommended_Mods#Required_Dependencies
    # Recommended
    - ModuleInserterSimplified
    - aai-vehicles-ironclad
    - grappling-gun
    - bullet-trails
    - equipment-gantry
    - textplates
    - combat-mechanics-overhaul
    - RecipeBook
    # QOL
    - even-distribution
    - AutoTrash
    - LogisticRequestManager
    - BottleneckLite
    # - Squeak Through
    - LogisticTrainNetwork
    # spaceX
    - alien-biomes
    - alien-biomes-hr-terrain
    - space-exploration-graphics
    - space-exploration-graphics-2
    - space-exploration-graphics-3
    - space-exploration-graphics-4
    - space-exploration-graphics-5
    - space-exploration-menu-simulations
    - shield-projector
    - aai-containers
    - aai-industry
    - aai-signal-transmission
    - simhelper
    - space-exploration-graphics
    - robot_attrition
    - informatron
    - jetpack
    - space-exploration # causes the crash
    - space-exploration-postprocess 
  # unofficial section is meant to just allow you to download and place folders into the mods folder.
  # we will not check version compatibility automatically with these downloads.
  # you can encounter an error if the file names dont match what the mod is expecting for example
  #Error Util.cpp:83: Failed to load mod "Squeak-Through": Filename of mod
  # /factorio/mods/Squeak-Through.zip doesn't match the expected Squeak Through_1.8.2.zip (case sensitive!)
  unofficial:
    - url: "https://github.com/Suprcheese/Squeak-Through/archive/refs/tags/1.8.2.zip"
      name: "Squeak Through_1.8.2.zip"
```

**Comment by SQLJames** [comment]
Hmm, I wonder if there is something different with that mod portal link or something. 
If you download the mod from from like a public GitHub repo or s3 bucket link I wonder if it works then. I'll have to dig into it a bit further to know what's happening.

**Comment by Scyattica** [comment]
Looking through the mod discord, I found your thread with the devs. They referenced the map gen settings file on startup.

Futher investigation shows that by default, we pass in this map_gen_settings.json file via a config map.

```
{"autoplace_controls":{},"cliff_settings":{"cliff_elevation_0":10,"cliff_elevation_interval":40,"name":"cliff","richness":1},"height":0,"peaceful_mode":false,"property_expression_names":{"control-setting:aux:bias":"0","control-setting:aux:frequency:multiplier":"1","control-setting:moisture:bias":"0","control-setting:moisture:frequency:multiplier":"1"},"seed":null,"starting_area":1,"starting_points":[{"x":0,"y":0}],"terrain_segmentation":1,"water":1,"width":0}
```

I looked into the code of the mode, and found this in space-exploration/shared.lua, referencing the defaults they provide with their map gen settings inside of the mod via the UI

```
Shared.se_default_mapgen = {
    order = "a",
    basic_settings = {
      water = 1.5, -- Water "coverage"
      autoplace_controls = {
        -- Nauvis climate
        hot = {size = 0.5},
        cold = {size = 0.5},
        -- Un-checks SE resources in the mapgen UI. SE resources are removed later anyway regardless of this,
        -- but it's a good visual indicator that these settings don't do anything.
        ["se-beryllium-ore"] = {size = 0},
        ["se-cryonite"] = {size = 0},
        ["se-holmium-ore"] = {size = 0},
        ["se-iridium-ore"] = {size = 0},
        ["se-methane-ice"] = {size = 0},
        ["se-naquium-ore"] = {size = 0},
        ["se-vitamelange"] = {size = 0},
        ["se-vulcanite"] = {size = 0},
        ["se-water-ice"] = {size = 0}
      },
      property_expression_names = {
        -- More Nauvis climate
        ["control-setting:moisture:bias"] = 0.05,
        ["control-setting:aux:bias"] = -0.35
      },
      starting_area = 2,
    },
    advanced_settings = {
      enemy_evolution =
      {
        time_factor =       0.0000005,
        destroy_factor =    0.0005,
        pollution_factor =  0.00000025
      },
      pollution =
      {
        ageing = 1,
        enemy_attack_pollution_consumption_modifier = 0.5
      },
    },
  }
```

Seeing all of this, I simply added this the below to my values.yaml file, and the helm chart deployed successfully and was able to start successfully.

```map_gen_settings:
  autoplace_controls:
    hot:
      size: 0.5
    cold:
      size: 0.5
```

**Comment by SQLJames** [comment]
I also responded to the discord thread, hopefully well get a full list of their recommended defaults.  As a temporary workaround we could copy a new generated save from the ui into the volume but that could be a bit tricky and extra work. The reason I would opt to go this way would be that if we are potentially missing any recommended defaults the game could be harder or easier than intended.

**Comment by SQLJames** [comment]
after speaking to some of the awesome members on the discord, they were able to help me with the setting merges. To keep all other things default, add the below code to your values.yaml file. This will pass in all their recommended defaults into the appropriate files and then allow you to start the game. This will generate the recommended mod settings into the map-settings.json and the map-gen-settings.json files (also shown below). I will be writing something up about this configuration. 

```
map_settings:
  pollution:
    enemy_attack_pollution_consumption_modifier: 0.5
  enemy_evolution:
    time_factor: 0.0000005
    destroy_factor: 0.0005
    pollution_factor: 0.00000025

map_gen_settings:
  water: 1.5
  starting_area: 2
  autoplace_controls: 
    hot:
      size: 0.5
    cold:
      size: 0.5
  property_expression_names:
    control-setting:moisture:bias: '0.05'
    control-setting:aux:bias: '-0.35'
```
map-gen-settings.json 
```
{
   "autoplace_controls":{
      "cold":{
         "size":0.5
      },
      "hot":{
         "size":0.5
      }
   },
   "cliff_settings":{
      "cliff_elevation_0":10,
      "cliff_elevation_interval":40,
      "name":"cliff",
      "richness":1
   },
   "height":0,
   "peaceful_mode":false,
   "property_expression_names":{
      "control-setting:aux:bias":"-0.35",
      "control-setting:aux:frequency:multiplier":"1",
      "control-setting:moisture:bias":"0.05",
      "control-setting:moisture:frequency:multiplier":"1"
   },
   "starting_area":2,
   "starting_points":[
      {
         "x":0,
         "y":0
      }
   ],
   "terrain_segmentation":1,
   "water":1.5,
   "width":0
}
```

map-settings.json 
```
{
   "difficulty_settings":{
      "recipe_difficulty":0,
      "research_queue_setting":"after-victory",
      "technology_difficulty":0,
      "technology_price_multiplier":1
   },
   "enemy_evolution":{
      "destroy_factor":0.0005,
      "enabled":true,
      "pollution_factor":2.5e-7,
      "time_factor":5e-7
   },
   "enemy_expansion":{
      "building_coefficient":0.1,
      "enabled":true,
      "enemy_building_influence_radius":2,
      "friendly_base_influence_radius":2,
      "max_colliding_tiles_coefficient":0.9,
      "max_expansion_cooldown":216000,
      "max_expansion_distance":7,
      "min_base_spacing":3,
      "min_expansion_cooldown":14400,
      "neighbouring_base_chunk_coefficient":0.4,
      "neighbouring_chunk_coefficient":0.5,
      "other_base_coefficient":2,
      "settler_group_max_size":20,
      "settler_group_min_size":5
   },
   "max_failed_behavior_count":3,
   "path_finder":{
      "cache_accept_path_end_distance_ratio":0.15,
      "cache_accept_path_start_distance_ratio":0.2,
      "cache_max_connect_to_cache_steps_multiplier":100,
      "cache_path_end_distance_rating_multiplier":20,
      "cache_path_start_distance_rating_multiplier":10,
      "direct_distance_to_consider_short_request":100,
      "enemy_with_different_destination_collision_penalty":30,
      "extended_collision_penalty":3,
      "fwd2bwd_ratio":5,
      "general_entity_collision_penalty":10,
      "general_entity_subsequent_collision_penalty":3,
      "goal_pressure_ratio":2,
      "ignore_moving_enemy_collision_distance":5,
      "long_cache_min_cacheable_distance":30,
      "long_cache_size":25,
      "max_clients_to_accept_any_new_request":10,
      "max_clients_to_accept_short_new_request":100,
      "max_steps_worked_per_tick":100,
      "max_work_done_per_tick":8000,
      "min_steps_to_check_path_find_termination":2000,
      "negative_cache_accept_path_end_distance_ratio":0.3,
      "negative_cache_accept_path_start_distance_ratio":0.3,
      "negative_path_cache_delay_interval":20,
      "overload_levels":[
         0,
         100,
         500
      ],
      "overload_multipliers":[
         2,
         3,
         4
      ],
      "short_cache_min_algo_steps_to_cache":50,
      "short_cache_min_cacheable_distance":10,
      "short_cache_size":5,
      "short_request_max_steps":1000,
      "short_request_ratio":0.5,
      "stale_enemy_with_same_destination_collision_penalty":30,
      "start_to_goal_cost_multiplier_to_terminate_path_find":500,
      "use_path_cache":true
   },
   "pollution":{
      "ageing":1,
      "diffusion_ratio":0.02,
      "enabled":true,
      "enemy_attack_pollution_consumption_modifier":0.5,
      "expected_max_per_chunk":150,
      "max_pollution_to_restore_trees":20,
      "min_pollution_to_damage_trees":60,
      "min_to_diffuse":15,
      "min_to_show_per_chunk":50,
      "pollution_per_tree_damage":50,
      "pollution_restored_per_tree_damage":10,
      "pollution_with_max_forest_damage":150
   },
   "steering":{
      "default":{
         "force_unit_fuzzy_goto_behavior":false,
         "radius":1.2,
         "separation_factor":1.2,
         "separation_force":0.005
      },
      "moving":{
         "force_unit_fuzzy_goto_behavior":false,
         "radius":3,
         "separation_factor":3,
         "separation_force":0.01
      }
   },
   "unit_group":{
      "max_gathering_unit_groups":30,
      "max_group_gathering_time":36000,
      "max_group_member_fallback_factor":3,
      "max_group_radius":30,
      "max_group_slowdown_factor":0.3,
      "max_member_slowdown_when_ahead":0.6,
      "max_member_speedup_when_behind":1.4,
      "max_unit_group_size":200,
      "max_wait_time_for_late_members":7200,
      "member_disown_distance":10,
      "min_group_gathering_time":3600,
      "min_group_radius":5,
      "tick_tolerance_when_member_arrives":60
   }
}
```
