### ISSUE TITLE
Unable to add a password to the game

### ISSUE THREAD

**Issue by Vanderscycle** [SQLJames/factorio-server-charts#25]
The image works really well, but I can't seem to lock down the server with a password despite specifying it in the `values.yaml` file. I suppose that I am making an obvious mistake, and would like a bit of help as to why its not working.

The relevant section of my `values.yaml`:
```yaml
server_settings:
  autosave_only_on_server: false
  name: '[BETA] helm-kubernetes-argocd-vanilla'
  description: 'unstable and experimental deployment method by me. Use at own risk and expect loss of data'
  tags:
    - vanilla
    - helm
    - experimental
  visibility:
    public: true
  require_user_verification: true

account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  [...]

serverPassword:
  # password required to log into the factorio server
  game_password: 'broski'
  # Existing Secret containing a `game_password` data entry
  passwordSecret: ''
  ```
  This results in the following `/factorio/configs/server-settings.json` which has no password. 
  ```json
  {
  "afk_autokick_interval": 0,
  "allow_commands": "admins-only",
  "auto_pause": true,
  "autosave_interval": 10,
  "autosave_only_on_server": false,
  "autosave_slots": 5,
  "description": "unstable and experimental deployment method by me. Use at own risk and expect loss of data",
  "ignore_player_limit_for_returning_players": false,
  "max_players": 0,
  "max_upload_in_kilobytes_per_second": 0,
  "max_upload_slots": 5,
  "maximum_segment_size": 100,
  "maximum_segment_size_peer_count": 10,
  "minimum_latency_in_ticks": 0,
  "minimum_segment_size": 25,
  "minimum_segment_size_peer_count": 20,
  "name": "[BETA] helm-kubernetes-argocd-vanilla",
  "non_blocking_saving": false,
  "only_admins_can_pause_the_game": true,
  "require_user_verification": true,
"game_password": "test",
  "tags": [
    "vanilla",
    "helm",
    "experimental"
  ],
  "visibility": {
    "lan": true,
    "public": true
  },
  "username": "...",
  "token": "..."
}
```
As far as I understand, I only need to fill the `game_password` value to add a password

**Comment by Vanderscycle** [comment]
I was able to change the password using `rcon` but its a roundabout way to do things:
`docker run --rm -it outdead/rcon ./rcon -a [...]:30100 -p [...]`

**Comment by Vanderscycle** [comment]
It also doesn't work when using `passwordSecret`. I have a sealed secret holding both `game_password` and `rconpw` 
```yaml
rcon:
  external: true
  passwordSecret: 'factorio-admin-secret'
[...]
```
and while I can change the rcon password using sealed-secrets I can't do the same for `game-password`
