### ISSUE TITLE
unable to start with Krastorio2 mod

### ISSUE THREAD

**Issue by digifuchsi** [SQLJames/factorio-server-charts#43]
Hey all,

I am unable to run a server using the latest Krastorio2 (v1.3.23) using the helm chart.
I am using a minimal values file:
```
image:
  tag: stable
service:
  type: ClusterIP
  port: 34197
persistence:
  enabled: true
  dataDir:
    Size: "10Gi"
  storageClassName: "ssd"
account:
  username: "secret"
  token: "secret"
mods:
  enabled: true
  portal:
    - Krastorio2
    - Krastorio2Assets
    - flib
```

But the pod keeps crashing with the following log output:
```
+ FACTORIO_VOL=/factorio
+ LOAD_LATEST_SAVE=true
+ GENERATE_NEW_SAVE=true
+ SAVE_NAME=replaceMe
+ BIND=
+ CONSOLE_LOG_LOCATION=
+ mkdir -p /factorio
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/configs
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/script-output
+ [[ ! -f /factorio/configs/rconpw ]]
+ [[ ! -f /factorio/configs/server-settings.json ]]
+ [[ ! -f /factorio/configs/map-gen-settings.json ]]
+ [[ ! -f /factorio/configs/map-settings.json ]]
++ find -L /factorio/saves -iname ++ '*.tmp.zip' wc -l
-mindepth 1
+ NRTMPSAVES=0
+ [[ 0 -gt 0 ]]
+ [[ false == \t\r\u\e ]]
++ id -u
+ [[ 0 = 0 ]]
+ usermod -o -u 845 factorio
usermod: no changes
+ groupmod -o -g 845 factorio
+ chown -R factorio:factorio /factorio
+ SU_EXEC='su-exec factorio'
+ sed -i '/write-data=/c\write-data=\/factorio/' /opt/factorio/config/config.ini
++ find -L /factorio/saves -iname ++ '*.zip' wc -l
-mindepth 1
+ NRSAVES=0
+ [[ true != true ]]
+ [[ true == true ]]
+ [[ -z replaceMe ]]
+ [[ -f /factorio/saves/replaceMe.zip ]]
+ su-exec factorio /opt/factorio/bin/x64/factorio --create /factorio/saves/replaceMe.zip --map-gen-settings /factorio/configs/map-gen-settings.json --map-settings /factorio/configs/map-settings.json
   0.000 2024-01-08 10:33:13; Factorio 1.1.100 (build 61920, linux64, headless)
   0.000 Operating system: Linux
   0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--create" "/factorio/saves/replaceMe.zip" "--map-gen-settings" "/factorio/configs/map-gen-settings.json" "--map-settings" "/factorio/configs/map-settings.json" 
   0.000 Config path: /opt/factorio/config/config.ini
   0.000 Read data path: /opt/factorio/data
   0.000 Write data path: /factorio [9725/9979MB]
   0.000 Binaries path: /opt/factorio/bin
   0.005 System info: [CPU: AMD EPYC 7232P 8-Core Processor, 2 cores, RAM: 3331 MB]
   0.005 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.005 Running in headless mode
   0.022 Loading mod settings Krastorio2 1.3.23 (settings.lua)
   0.023 Loading mod settings Krastorio2 1.3.23 (settings-updates.lua)
   0.024 Loading mod core 0.0.0 (data.lua)
   0.045 Loading mod base 1.1.100 (data.lua)
   0.218 Loading mod flib 0.13.0 (data.lua)
   0.239 Loading mod Krastorio2 1.3.23 (data.lua)
   0.327 Loading mod base 1.1.100 (data-updates.lua)
   0.351 Loading mod Krastorio2 1.3.23 (data-updates.lua)
   0.428 Loading mod Krastorio2 1.3.23 (data-final-fixes.lua)
   0.555 Checksum for core: 2152183905
   0.555 Checksum of base: 1215362964
   0.555 Checksum of flib: 574468295
   0.555 Checksum of Krastorio2Assets: 0
   0.555 Checksum of Krastorio2: 3880386261
   0.790 Prototype list checksum: 2900857415
   0.856 Info PlayerData.cpp:76: Local player-data.json available, timestamp 1704709973
   0.856 Info PlayerData.cpp:83: Cloud player-data.json unavailable
   0.857 Factorio initialised
   0.857 Info Main.cpp:777: Creating new map /factorio/saves/replaceMe.zip
   2.076 Loading level.dat: 1608873 bytes.
   2.076 Info Scenario.cpp:204: Map version 1.1.100-0
   2.112 Checksum for script /factorio/temp/currently-playing/control.lua: 3702463597
   2.120 Checksum for script __Krastorio2__/control.lua: 2424813832
Error: The mod Krastorio 2 (1.3.23) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Krastorio2::on_init()
__Krastorio2__/scripts/freeplay.lua:52: attempt to index field 'autoplace_controls' (a nil value)
stack traceback:
	__Krastorio2__/scripts/freeplay.lua:52: in function 'add_to_crash_site'
	__Krastorio2__/scripts/migrations.lua:23: in function 'generic'
	__Krastorio2__/control.lua:54: in function <__Krastorio2__/control.lua:37>
   2.172 Goodbye
```

When I run the container in docker using `factoriotools/factorio:stable` as an image and adding the same mods manually everything runs fine.

Does this helm chart needs some special settings to run Krastorio2?
Anyone experienced similar issues and may give me an hint where the issue may be?

FYI: using no mods or other mods everything works just fine.

Thanks!

**Comment by digifuchsi** [comment]
After comparing the map-gen config files I noticed that `autoplace_controls` is empty when creted by the helm chart. After defining the default values the pod is created and running fine:
```
map_gen_settings:
  autoplace_controls:
    coal:
      frequency: 1
      size: 1
      richness: 1
    stone:
      frequency: 1
      size: 1
      richness: 1
    copper-ore:
      frequency: 1
      size: 1
      richness: 1
    iron-ore:
      frequency: 1
      size: 1
      richness: 1
    uranium-ore:
      frequency: 1
      size: 1
      richness: 1
    crude-oil:
      frequency: 1
      size: 1
      richness: 1
    trees:
      frequency: 1
      size: 1
      richness: 1
    enemy-base:
      frequency: 1
      size: 1
      richness: 1
```

Should this be set by default or why is `autoplace_controls` set to be empty?
