### ISSUE TITLE
Issues with helm values schema

### ISSUE THREAD

**Issue by Kariton** [SQLJames/factorio-server-charts#75]
My current deployment does not update with the updated schema.

> Error: values don't meet the specifications of the schema(s) in the following chart(s): factorio-server-charts: - map_gen_settings.seed: Invalid type. Expected: null, given: integer - map_gen_settings.starting_area: Invalid type. Expected: integer, given: number

```yaml
        map_gen_settings:
          starting_area: 1.5
          peaceful_mode: false
          autoplace_controls:
            iron-ore:
              frequency: 0.50
              size: 1.50
              richness: 2
            copper-ore:
              frequency: 0.50
              size: 1.50
              richness: 2
            stone:
              frequency: 0.50
              size: 1.50
              richness: 2
            coal:
              frequency: 0.50
              size: 1.50
              richness: 2
            crude-oil:
              frequency: 0.50
              size: 1.50
              richness: 2
            uranium-ore:
              frequency: 0.50
              size: 1.50
              richness: 2
          seed: 3508092348
```
